# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME: "esim2gobucket"
  EB_APPLICATION_NAME: "Flaskapp"
  EB_ENVIRONMENT_NAME: "Flaskapp-env" 
  DEPLOY_PACKAGE_NAME: "flask-app-${{ github.sha }}.zip"
  AWS_REGION_NAME: "us-east-1"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  my_ci_pipeline:
      runs-on: ubuntu-latest
      
      steps: 
        - name: Git clone our repository
          uses: actions/checkout@v1
          
        - name: Create ZIP deployment package
          run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

        - name: Configure my AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
            aws-region: ${{ env.AWS_REGION_NAME }}
            
        - name: Copy our Deployment package to S3 bucket
          run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
          
        - name: Print nice message on completoin of CI Pipeline
          run: echo "CI Pipeline part finished successfully"
